### ISSUE TITLE
Diagram design: Standard colours and fonts

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/UML-Best-Practices#1]
TBD: ISO/TC211 should have standard colours and fonts in UML diagrams. Ref INSPIRE Repository tutorial page 16-17: 
https://github.com/ISO-TC211/UML-Best-Practices/blob/master/Reference%20material/INSPIRE_UML_repository_tutorial.pdf

**Comment by jetgeo** [comment]
Recommendation 15 in ISO/DIS19103:
For the diagrams, readability concerns should be taken into account. Font size
should be no smaller than 8 points after diagram scale is taken into account (a 12 pt
font at 90% is 12*0.9 = 10.8 pt).
Also relates to https://github.com/ISO-TC211/UML-Best-Practices/wiki/Less-is-more

**Comment by jetgeo** [comment]
Note from Southampton: Figures in ISO standards (documents) shall not have colours. But the HM can have colours. Ask Sparx about the possibility of having different colours on attributes. Describe how to use colours etc. Ref OS Road map. When using colours: Provide a key

**Comment by heidivanparys** [comment]
Page started: https://github.com/ISO-TC211/UML-Best-Practices/wiki/Colors-and-fonts

**Comment by jetgeo** [comment]
Colors or colours? (American or European)?

**Comment by jetgeo** [comment]
From ISO19160-1:
Diagrams in the documentation should be prepared as follows:
− To distinguish between base classes and profile-specific classes, it is recommended that a
transparent background be used for (base) classes from the address model, and a shaded fill colour
background for the profile-specific classes.
− Diagrams should use a similar locational pattern (i.e. AddressSpecification at the left top, Address
and AddressableObject underneath it, AddressComponent and ReferenceObject on the right hand
side) to the one used for the address model in Figures 1 to 4 of this document.

**Comment by jetgeo** [comment]
Done. Changed from colors (US) to colours (european).
