### ISSUE TITLE
Required and recomended diagrams

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/UML-Best-Practices#16]
What diagrams are required, ref 19103:2013 6.16

Requirement 18,19,20,21
Recomendation 15, 16

**Comment by jetgeo** [comment]
Recommendation 16:
For each package it is recommended to have a class diagram for the entire package
(without any associations, operations or attributes shown).

Requirement 18:
All classifiers shall be documented in a "context diagram" where all attributes,
operations and all relationships that are navigable from the central classifier are
displayed.

Requirement 19: 
Each classifier shall have a definition describing its intended meaning or semantics.
(relates to https://github.com/ISO-TC211/UML-Best-Practices/wiki/Best-practices-for-modelling - definitions)

Requirement 20:
Each package, class, operation, attribute, association role, association and constraint shall have a textual description in the text near its context diagram.
(documentation, not UML?)

Requirement 21:
Package dependency diagrams shall be included, including external package dependencies.

Also:
Overview diagrams consisting of all major classes in a document may be included if found feasible. Overview diagrams can focus on the most important parts of the model, and package diagrams can also give a full and complete picture of the whole package content.

**Comment by jetgeo** [comment]
Started here: https://github.com/ISO-TC211/UML-Best-Practices/wiki/Required-diagrams

**Comment by jetgeo** [comment]
Finished, but should have had illustrations?

**Comment by jetgeo** [comment]
Note from Southampton:
- Recomend to use use case diagrams for setting up use cases, instance diagrams for testing the model
- Add illustrations
- High-level introduction diagrams instead of none-UML diagrams

**Comment by rmurcott** [comment]
An example of instance diagrams being mandatory:
ISO/DIS 19160-1 Addressing — Part 1: Conceptual model, 7.5.2 Requirements and recommendations; 13) Diagrams of instance data (examples) for a few sample addresses **shal**l be included.

**Comment by jetgeo** [comment]
More from ISO/DIS19160-1: 
The address profile documentation shall contain the following:
...
6) The following elements of the profile model in at least one diagram:
i) Each mandatory class (Address, AddressComponent), conditional class and optional class in the
profile.
ii) Each profile-specific class, type or codelist derived from a class, type or codelist in the address
model.
iii) Each mandatory, optional, conditional and profile-specific association in the profile.
iv) Each mandatory, optional, conditional and profile-specific attribute in the profile.
...
10) Diagrams of instance data (examples) for a few sample addresses.

**Comment by jetgeo** [comment]
Done, except Use Case diagrams. https://github.com/ISO-TC211/UML-Best-Practices/wiki/Required-diagrams.
