### ISSUE TITLE
Useful scripts and tools

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/UML-Best-Practices#4]
Collect useful Enterprise Architect scripts and other tools.

Examples: 
- Shapechange plugin
- Scripts from Geodatastyrelsen (Heidi)
- Scripts from NPRA (Knut)
- Ordonance Survey (Debbie)

How to write scripts - reference material

**Comment by jetgeo** [comment]
Examples: 
Sorting of elements in a package
Identify attributes without ClassifierID

**Comment by heidivanparys** [comment]
Started writing these pages about [useful tools](../wiki/Useful tools for use in or together with Enterprise Architect) and [searches](../wiki/Model searches in Enterprise Architect).

**Comment by jetgeo** [comment]
Added a few scripts in https://github.com/ISO-TC211/UML-Best-Practices/tree/master/Scripts

TODO: Write about scripts and reference material on https://github.com/ISO-TC211/UML-Best-Practices/wiki/Scripts%20in%20Enterprise%20Architect

**Comment by jetgeo** [comment]
Think we can close this and keep adding scripts.
