### ISSUE TITLE
Best practices to help implementation -  just a couple of suggested edits

### ISSUE THREAD

**Issue by rmurcott** [ISO-TC211/UML-Best-Practices#42]
**Best practices to help implementation**
Re:
[https://github.com/ISO-TC211/UML-Best-Practices/wiki/Best-practices-to-help-implementation]

A couple of suggested edits ... 

**from:** This page describes important modelling issues that will influence how models can be _implemendet_. 
**to:** This page describes important modelling issues that will influence how models can be implemented.

**from:** Dependencies - avoid dependencies that _makes_ implementation _unecessary_ complex
**to:** Dependencies - avoid dependencies that make implementation unnecessarily complex

**Comment by jetgeo** [comment]
Thank you Richard, I have updated the page.
