### ISSUE TITLE
EA-documentation template - bugs/improvements 

### ISSUE THREAD

**Issue by magnusKarge** [ISO-TC211/UML-Best-Practices#46]
Using the EA-template (https://github.com/ISO-TC211/UML-Best-Practices/raw/master/DocumentationOfUMLModels/EA-template/ISOTC11_EA_report_template.zip) I noticed three things that could need some improvement.

1. In the situation where class A is subtype of class B but class A is not supertype of any other class, in the "SuperType of:"-part of class A's documentation class A's name appears, which looks like a bug. For classes without any generalizations or only subtypes this seems to work.
2. My colleagues and I consider it more useful to have information about the supertype(s) of a class than a list of subtypes of a class. So instead of (or additionally to) the "SuperType of:"-part we suggest to add a "SubType of:"-part.
3. Remove "ISO/DIS 19135-1" from the header.

**Comment by magnusKarge** [comment]
Please find attached a slightly improved version. This one does not include the bug described in [1] in my comment above.
[ISOTC211_documentation_template_improved.zip](https://github.com/ISO-TC211/UML-Best-Practices/files/2044665/ISOTC211_documentation_template_improved.zip)

**Comment by sptws001** [comment]
Good afternoon,
I came across this open issue and I was wondering if your team had undertaken any work to improve the documentation template beyond the improved template you provided. If you feel this is no longer required, or was addressed and not closed, I can address this for you.

Most of my model reporting has tended to be at a lower level - directly querying the model repository database or running transforms against the XMI-based model export. There are aspects of the RTF reporting structure that are a bit painful to work with.

Regardless, I am fully supportive of more robust documentation templates so if you could identify some of the key information you would like incorporated into the reporting template, I can begin looking into this for you.

Thanks
Tobias

**Comment by sptws001** [comment]
Users have migrated to ShapeChange and this request is not longer required.
