### ISSUE TITLE
Spellcheck corrections suggested for the UML BP Wiki

### ISSUE THREAD

**Issue by tobiasspears** [ISO-TC211/UML-Best-Practices#49]
Good morning,
I cloned the Wiki for the UML BP project and ran a batch spellcheck to look for any typographic issues as I noticed a few as I was visiting the individual pages.

I have attached the report as an Excel workbook and prefiltered the main false positives:
[ISO-UML-BP_Wiki_Spellcheck.xlsx](https://github.com/ISO-TC211/UML-Best-Practices/files/4317027/ISO-UML-BP_Wiki_Spellcheck.xlsx)

You can see the full list of reported errors by clicking the filter button for the first column in the spreadsheet.

Thanks!

Tobias

**Comment by jetgeo** [comment]
I have invited you in as a member of the HMMG team on GitHub now. You may then edit and fix these typos yourself :).

**Comment by tobiasspears** [comment]
Thanks Knut,
Can you invite my Google user to the projects: spearstobias@gmail.com<mailto:spearstobias@gmail.com>?

Thanks!

Tobias

**Comment by sptws001** [comment]
Potential typos were reviewed and updates as apropriate. An updated version of the original list is attached, noting the decisions on individual changes. Other minor typos were also identified and corrected through the process and are not included in the orignal checklist.

[ISO-UML-BP_Wiki_Spellcheck.xlsx](https://github.com/ISO-TC211/UML-Best-Practices/files/4377964/ISO-UML-BP_Wiki_Spellcheck.xlsx)
