### ISSUE TITLE
Naming of packages, classes and attributes

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/UML-Best-Practices#6]
Use some text from the desciption of important changes in the new 19107, regarding not using prefixes

Rules from standards - camelcase etc.

**Comment by jetgeo** [comment]
Note from the meeting in Southampton: Real world name vs UML names. Using tagged values and aliases.

**Comment by jetgeo** [comment]
Prefixes have some value too - ref discussion on https://github.com/ISO-TC211/19115-2Revision/issues/19

**Comment by jetgeo** [comment]
Agenda item at the HMMG meeting i Sydney. 
Todo: Find all prefixes used now, try to set up some rules.

**Comment by smrgeoinfo** [comment]
The prefixes are redundant; namespaces meet the requirements that  motivated the introduction of the prefixes.  If a class name is to be redefined (not imported) in a model, it should be given a name that distinguishes it from the other class.

**Comment by jetgeo** [comment]
I agree with Steve, except that prefixes may have some value for human readability of the models.

**Comment by jetgeo** [comment]
https://github.com/ISO-TC211/UML-Best-Practices/wiki/Naming-of-packages,-classes-and-attributes

**Comment by jetgeo** [comment]
Closed, but referenced in https://github.com/ISO-TC211/UML-Best-Practices/issues/29
