### ISSUE TITLE
Writing constraints

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/UML-Best-Practices#8]
https://github.com/ISO-TC211/UML-Best-Practices/wiki/Constraints

More details and examples for writing OCL?

OCL: ref INSPIRE Repository tutorial page 10-11
Display: ref ref INSPIRE Repository tutorial page 14

https://github.com/ISO-TC211/UML-Best-Practices/blob/master/Reference%20material/INSPIRE_UML_repository_tutorial.pdf

**Comment by jetgeo** [comment]
Notes from Southampton: 
Constraints on attributes: Don't.
Validator for OCL in EA is limited. Tool for writing OCL in EA? (Ask Sparx)

**Comment by PalmJanssen** [comment]
In addition:
Constraints on attributes must be formulated at the level (context) of classes.

**Comment by jetgeo** [comment]
Ref also text about constraints in ISO19109:2015

**Comment by jetgeo** [comment]
Done. https://github.com/ISO-TC211/UML-Best-Practices/wiki/Constraints
